# Introdução NumPy:

In [2]:
import numpy as np
# obs.: também poderíamos importar tudo do módulo:
# from numpy import *
# caso não tiver instalado utilizar o comando !pip install numpy

## Vetores:

In [3]:
vetor = np.array([3, 8, 5, 12])

print('vetor:', vetor)
# Shape mostra as dimensões do array:
print('dimensão:', vetor.shape)

vetor: [ 3  8  5 12]
dimensão: (4,)


In [4]:
# Também podemos especificar o tipo das variáveis dentro do array:
vetor_float = np.array([1, 0.1, 0.01, 0.001])
print("Vetor:", vetor_float, "   Dimensão:", vetor_float.shape, "   Tipo:", vetor_float.dtype)

print()

vetor_int = np.array([1, 1, 2, 3, 5, 8], np.uint8)
print("Vetor:", vetor_int, "               Dimensão:", vetor_int.shape, "   Tipo:", vetor_int.dtype)

Vetor: [1.    0.1   0.01  0.001]    Dimensão: (4,)    Tipo: float64

Vetor: [1 1 2 3 5 8]                Dimensão: (6,)    Tipo: int32


## Matrizes:

In [5]:
matriz = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print('matriz:', matriz)
print('dimensão:', matriz.shape)

matriz: [[1 2 3]
 [4 5 6]
 [7 8 9]]
dimensão: (3, 3)


## Geração de Arrays:

In [7]:
array_3x3_um = np.ones((3, 3))
print('array 3x3 com uns\n', array_3x3_um)

array_2x3x3_zero = np.zeros((2, 3, 3))
print('array 2x3x3 com zeros\n', array_2x3x3_zero)

array_faixa = np.arange(0, 100, 10)
print('array de 0 à 100 de 10 em 10\n', array_faixa)

#np.random.seed(20)
array_4x4_aleatorio = np.random.randint(10, size=(4, 4))
print('array 4x4 aleatorio de 0 à 10\n', array_4x4_aleatorio)

array 3x3 com uns
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
array 2x3x3 com zeros
 [[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
array de 0 à 100 de 10 em 10
 [ 0 10 20 30 40 50 60 70 80 90]
array 4x4 aleatorio de 0 à 10
 [[3 9 4 6]
 [7 2 0 6]
 [8 5 3 0]
 [6 6 0 9]]


#### Transposta e concatenação:

In [7]:
matriz_2x3 = np.array([[0, 1, 2], [3, 4, 5]])
print('Matriz 2x3:')
print(matriz_2x3)

print('\nTransposta:')
print(matriz_2x3.T)

matriz_2x2 = np.array([[6, 7], [8, 9]])
print('\nMatriz 2x2:')
print(matriz_2x2)

matriz_3x3 = np.array([[6, 7, 8], [9, 10, 11], [12, 13, 14]])
print('\nMatriz 3x3:')
print(matriz_3x3)

Matriz 2x3:
[[0 1 2]
 [3 4 5]]

Transposta:
[[0 3]
 [1 4]
 [2 5]]

Matriz 2x2:
[[6 7]
 [8 9]]

Matriz 3x3:
[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


#### Indexação:

A indexação funciona da mesma forma que listas normais do Python:

In [8]:
# Elementos individuais:
matriz_4x3 = np.array([[0,  1,  2],
                       [3,  4,  5],
                       [6,  7,  8],
                       [9, 10, 11]])

print("Linha de índice 0:", matriz_4x3[0]) # linha de índice 0
print("Linha 2 e coluna 1:", matriz_4x3[2, 1]) # linha de índice 2 ([6, 7, 8]) e coluna de índice 1
print("Todas linhas e coluna 1:", matriz_4x3[:, 1]) # todas as linhas e coluna de índice 1
print("Linhas [1, 3) e colunas >= 1:\n", matriz_4x3[1:3, 1:]) # linhas [1, 3), todas as colunas a partir de 1

Linha de índice 0: [0 1 2]
Linha 2 e coluna 1: 7
Todas linhas e coluna 1: [ 1  4  7 10]
Linhas [1, 3) e colunas >= 1:
 [[4 5]
 [7 8]]
